### PR TITLE
Add concat operation for webgl2 compute backend.

### PR DESCRIPTION
**Pull request by haoyunfeix**

### CODE REVIEW

**Comment by haoyunfeix** [comment]
4 cases passed 2, investigating the failure ones.

**Comment by haoyunfeix** [comment]
All 41 concat test cases got passed
@qjia7 PTAL

**Comment by haoyunfeix** [comment]
@qjia7 PTAL
I updated shader_preprocessor to generate same shader code as webgpu and remove unnessary changing in kernel/concat.ts

**Comment by qjia7** [comment]
LGTM. Thanks.

**Comment by qjia7** [comment]
Sorry, Just notice that you are using CR LF instead of LF at the end of line. So you will see a lots of '^M' in your new added file `concat.ts` in console mode. I added a small patch to fix it. Please set EOL mode to LF in your VS Code in case we meet same issue in future.

**Comment by haoyunfeix** [comment]
> Sorry, Just notice that you are using CR LF instead of LF at the end of line. So you will see a lots of '^M' in your new added file `concat.ts` in console mode. I added a small patch to fix it. Please set EOL mode to LF in your VS Code in case we meet same issue in future.

Got it!

**Pull request merged**
