### PR TITLE
[merge] conv2d_mm: Fix dispatch dimensions

### PR DESCRIPTION
**Pull request by axinging**
This change guarantees below test case run correctly. But leads to significant performance regression on some case.
Test case: https://github.com/tensorflow/tfjs-core/pull/1745/files#diff-15289bfca30229483003cbaea418596aR191.
Merged from: https://github.com/tensorflow/tfjs-core/pull/1745.

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @haoyunfeix @xhcao PTAL

**Comment by qjia7** [comment]
I notice that the performance becomes very bad with this fixing. @axinging Do you mind to test webgpu's performance on Mac for this operator?

**Comment by axinging** [comment]
Rebase and update comments.
@qjia7 @haoyunfeix @xhcao PTAL
One thing puzzled me is test case https://github.com/tensorflow/tfjs-core/pull/1745/files#diff-15289bfca30229483003cbaea418596aR191 is no more used in https://github.com/tensorflow/tfjs-core/blob/master/src/ops/conv2d_test.ts.

**Comment by qjia7** [comment]
LGTM. Thanks.

**Pull request merged**
